const content = {
  uz: {
    headerNav: ["Uy", "Ilovalar", "Guvohlar", "Shifokorni qidirish", "Biz haqimizda"],
    heroTitle: " Siz uchun virtual sog'liqni saqlash",
    heroText: "Trafalgar ilg'or va arzon tibbiy xizmatni taqdim etadi, har bir kishi uchun mobil va onlayn foydalanish mumkin",
    heroButton: "Bugun maslahatlashing",
    ourServices: "Bizning xizmatlar",
    ourServicesText: "Biz siz uchun eng yaxshi tanlovlarni taqdim etamiz. Buni sog'lig'ingizga moslashtiring va yuqori malakali shifokorlarimiz bilan davolanishingizga ishonch hosil qiling, biz bilan maslahatlashishingiz mumkin bo'lgan xizmat turi sog'lig'ingizga mos keladi.",
    ourServicesListTitle: ["Shifokorni qidirish", "Onlayn dorixona", "Konsultatsiya", "Tafsilotlar ma'lumotlari", "Shoshilinch tibbiy yordam", "Kuzatuv",],
    ourServicesListText: ["Minglab mutaxassis, umumiy va ishonchli shifoxonalardan shifokoringizni tanlang", "Dori-darmonlaringizni oddiy yetkazib berish tizimiga ega mobil ilovamiz orqali xarid qiling", "Ishonchli shifokorlarimiz bilan bepul maslahatlashing va eng yaxshi tavsiyalarni oling", "Ishonchli shifokorlarimiz bilan bepul maslahatlashing va eng yaxshi tavsiyalarni oling", "Siz o'zingiz yoki farzandlaringiz va sevimli oilangiz uchun 24/7 tez yordam olishingiz mumkin", "Tibbiy tarix va salomatlik maʼlumotlarini kuzatib boring va saqlang",],
    learnMore: "Batafsil ma'lumot",
    providersTitle: "Etakchi sog'liqni saqlash provayderlari",
    providerText: "Trafalgar ilg'or va arzon tibbiy xizmatni taqdim etadi, har bir kishi uchun mobil va onlayn foydalanish mumkin. Biz uchun bu shunchaki ish emas. Biz taqdim etayotgan yechimlarimiz bilan faxrlanamiz",
    mobileAppsTitle: "Mobil ilovalarimizni yuklab oling",
    mobileAppsText: "Bizning maxsus bemorni jalb qilish ilovamiz va veb-portalimiz sizga ma'lumotlarga bir zumda (zerikarli shakl, uzoq qo'ng'iroqlar yoki ma'muriy qiyinchiliksiz) va xavfsiz kirish imkonini beradi.",
    download: "Yuklab olish",
    customersTitle: "Bizning mijozimiz nima deyapti",
    whichCustomer: "Edvard Nyugeyt",
    whoCustomer: "Ta'sischilar doirasi",
    customerQuote: "“Bizning bemorlarni jalb qilish uchun maxsus ilovamiz va veb-portalimiz sizga ma'lumotlarga bir zumda (zerikarli shakl, uzoq qo'ng'iroqlar yoki ma'muriy qiyinchiliksiz) va xavfsiz kirish imkonini beradi”",
    article: "Bizning so'nggi maqolamizni ko'rib chiqing",
    articleTitle: ["Kasallikni aniqlash, laboratoriyada tekshirish", "Iste'mol qilish uchun xavfsiz bo'lgan o'simlik ", "Sog'lom yuz terisi uchun tabiiy parvarish",],
    articleText: ["Bunday holda, kasallikni aniqlashda sog'liqni saqlash laboratoriyasining roli juda muhim ", "Hozirgi vaqtda o'simlik dori-darmonlari juda keng qo'llaniladi, chunki u sog'liq uchun juda foydali ", "Sog'lom turmush tarzini hozirdan boshlash kerak, shuningdek, terining salomatligi uchun.",],
    readMore: "Ko'proq o'qish",
    viewAll: "Hammasini ko'rish",
    footerInfo: "Trafalgar ilg'or va arzon tibbiy xizmatni taqdim etadi, har bir kishi uchun mobil va onlayn foydalanish mumkin",
    allRights: "Barcha huquqlar himoyalangan",
    company : [
      "Kompaniya",
      "kompaniya Haqida",
      "Tasdiqlashlar",
      "Doktor toping",
      "Ilovalar",
    ],
    region: [
      "mintaqa",
      "Indoneziya",
      "Singapur",
      "Gonkong",
      "Kanada",
    ],
    help: [
      "Yordam",
      "Yordam markazi",
      "Ko'mak bilan bog'laning",
      "Ko'rsatmalar",
      "U qanday ishlaydi",
    ],
  },
  en: {
    headerNav: ["Home", "Apps", "Testimonials", "Find a doctor", "About us"],
    heroTitle: " Virtual healthcare for you",
    heroText: "Trafalgar provides progressive, and affordable healthcare, accessible on mobile and online for everyone",
    heroButton: "Consult today",
    ourServices: "Our services",
    ourServicesText: "We provide to you the best choiches for you. Adjust it to your health needs and make sure your undergo treatment with our highly qualified doctors you can consult with us which type of service is suitable for your health",
    ourServicesListTitle: ["Search doctor", "Online pharmacy", "Consultation", "Details info", "Emergency care", "Tracking",],
    ourServicesListText: ["Choose your doctor from thousands of specialist, general, and trusted hospitals", "Buy  your medicines with our mobile application with a simple delivery system", "Free consultation with our trusted doctors and get the best recomendations", "Free consultation with our trusted doctors and get the best recomendations", "You can get 24/7 urgent care for yourself or your children and your lovely family", "Track and save your medical history and health data",],
    learnMore: "Learn more",
    providersTitle: "Leading healthcare providers",
    providerText: "Trafalgar provides progressive, and affordable healthcare, accessible on mobile and online for everyone. To us, it’s not just work. We take pride in the solutions we deliver",
    mobileAppsTitle: "Download our mobile apps",
    mobileAppsText: "Our dedicated patient engagement app and  web portal allow you to access information instantaneously (no tedeous form, long calls, or administrative hassle) and securely",
    download: "Download",
    customersTitle: "What our customer are saying",
    whichCustomer: "Edward Newgate",
    whoCustomer: "Founder Circle",
    customerQuote: "“Our dedicated patient engagement app and  web portal allow you to access information instantaneously (no tedeous form, long calls, or administrative hassle) and securely”",
    article: "Check out our latest article",
    articleTitle: ["Disease detection, check up in the laboratory", "Herbal medicines that are safe for consumption", "Natural care for healthy facial skin",],
    articleText: ["In this case, the role of the health laboratory is very important to do a disease detection...", "Herbal medicine is very widely used at this time because of its very good for your health...", "A healthy lifestyle should start from now and also for your skin health.There are some...",],
    readMore: "Read more",
    viewAll: "View all",
    footerInfo: "Trafalgar provides progressive, and affordable healthcare, accessible on mobile and online for everyone",
    allRights: "All rights reserved",
    company : [
      "Company",
      "About",
      "Testimonials",
      "Find a doctor",
      "Apps",
    ],
    region: [
      "Region",
      "Indonesia",
      "Singapore",
      "Hongkong",
      "Canada",
    ],
    help: [
      "Help",
      "Help center",
      "Contact support",
      "Instructions",
      "How it works",
    ],
  },
  ru: {
    headerNav: ["Дом", "Программы", "Отзывы", "Найти врача", "О нас"],
    heroTitle: " Виртуальное здравоохранение для вас",
    heroText: "Трафальгар предоставляет прогрессивное и доступное медицинское обслуживание, доступное на мобильных устройствах и в Интернете для всех.",
    heroButton: "Проконсультируйтесь сегодня",
    ourServices: "Наши сервисы",
    ourServicesText: "Мы предлагаем вам лучший выбор. Настройте его в соответствии с потребностями вашего здоровья и убедитесь, что вы проходите лечение у наших высококвалифицированных врачей, вы можете проконсультироваться с нами, какой вид услуг подходит для вашего здоровья.",
    ourServicesListTitle: ["Поиск врача", "Интернет-аптека", "Консультация", "Подробная информация", "Неотложная помощь", "Отслеживание",],
    ourServicesListText: ["Выберите своего врача из тысяч специализированных, общих и надежных больниц.", "Покупайте лекарства с помощью нашего мобильного приложения с простой системой доставки", "Бесплатная консультация у наших проверенных врачей и получение лучших рекомендаций", "Бесплатная консультация у наших проверенных врачей и получение лучших рекомендаций", "Вы можете получить круглосуточную неотложную медицинскую помощь для себя, своих детей и любимой семьи.", "Отслеживайте и сохраняйте свою историю болезни и данные о здоровье",],
    learnMore: "Учить больше",
    providersTitle: "Ведущие поставщики медицинских услуг",
    providerText: "Трафальгар предоставляет прогрессивное и доступное медицинское обслуживание, доступное для всех на мобильных устройствах и в Интернете. Для нас это не просто работа. Мы гордимся предлагаемыми нами решениями",
    mobileAppsTitle: "Загрузите наши мобильные приложения",
    mobileAppsText: "Наше специальное приложение для взаимодействия с пациентами и веб-портал позволяют мгновенно и безопасно получать доступ к информации (без лишних форм, длительных звонков или административных хлопот).",
    download: "Скачать",
    customersTitle: "Что говорят наши клиенты",
    whichCustomer: "Эдвард Ньюгейт",
    whoCustomer: "Основатель Circle",
    customerQuote: "«Наше специальное приложение для взаимодействия с пациентами и веб-портал позволяют мгновенно и безопасно получить доступ к информации (без лишних форм, длительных звонков или административных хлопот)»",
    article: "Ознакомьтесь с нашей последней статьей",
    articleTitle: ["Выявление заболеваний, проверка в лаборатории", "Безопасные для употребления лекарственные травы", "Натуральный уход за здоровой кожей лица",],
    articleText: ["В этом случае роль лаборатории здравоохранения очень важна для выявления заболеваний ...", "В настоящее время очень широко используются лечебные травы, потому что они ", "Здоровый образ жизни должен начинаться с этого момента, а также для здоровья вашей кожи. Есть некоторые ...",],
    readMore: "Подробнее",
    viewAll: "Посмотреть все",
    footerInfo: "Трафальгар предоставляет прогрессивное и доступное медицинское обслуживание, доступное на мобильных устройствах и в Интернете для всех.",
    allRights: "Все права защищены",
    company : [
      "Компания",
      "о компании",
      "Отзывы",
      "Найди врача",
      "Программы",
    ],
    region: [
      "Область",
      "Индонезия",
      "Сингапур",
      "Гонконг",
      "Канада",
    ],
    help: [
      "Помощь",
      "Центр помощи",
      "Контактная поддержка",
      "Инструкции",
      "Как это работает",
    ],
  },
};

export default content;